### ISSUE TITLE
ProtocolBuffer support for newer versions of heka

### ISSUE THREAD

**Issue by jsh2134** [thekashifmalik/heka-py#1]
the last mention of ProtocolBuffer in the changelog matches hekad 0.4.0

I've created a custom socket logger to add to a Django project to send messages to Heka. Unfortunately it seems to only pull the timestamp from the message.

I would love to update the ProtocolBuffer to heka 0.9.x - any guidance would be appreciated.

**Comment by rafrombrc** [comment]
I don't think there have been any changes to the Heka protobuf schema since before heka 0.4.0. In any event, the code in this repo should be generating valid Heka protobuf streams. I just did a quick test locally to verify: https://rmiller.pastebin.mozilla.org/8839230

It's likely that the problem is elsewhere, possibly in the framing. If you can point to snippets of your code that is sending data to Heka, as well as the config of the Heka server that is receiving the data we can probably help you figure out what's wrong.

**Comment by jsh2134** [comment]
Thanks for the quick reply! I was missing framing but a more glaring issue was that I wasn't including a `payload` in the message. This stumped us for a while. The example code in the README https://github.com/kalail/heka-py/blob/master/README.rst#getting-started leaves that value out. The Message class defaults to `''` but the it wasn't processed correctly by the decoder on our central heka host server.

This is the final working SocketHandler class https://gist.github.com/jsh2134/14027c69464498bc8ed2

**Comment by thekashifmalik** [comment]
It looks like this got resolved!

**Comment by jsh2134** [comment]
:+1:
